/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 33
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 19
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_SEMI = 1,
  sym_automata = 2,
  sym_name = 3,
  sym_alphabet = 4,
  sym_exec = 5,
  anon_sym_COMMA = 6,
  anon_sym_DASH = 7,
  anon_sym_DOT = 8,
  anon_sym_COLONs = 9,
  anon_sym_COLONf = 10,
  anon_sym_COLONsf = 11,
  sym_source_file = 12,
  sym_automata_desc = 13,
  sym_statements = 14,
  sym_statement = 15,
  sym_state_spec = 16,
  aux_sym_source_file_repeat1 = 17,
  aux_sym_statements_repeat1 = 18,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_SEMI] = ";",
  [sym_automata] = "automata",
  [sym_name] = "name",
  [sym_alphabet] = "alphabet",
  [sym_exec] = "exec",
  [anon_sym_COMMA] = ",",
  [anon_sym_DASH] = "-",
  [anon_sym_DOT] = ".",
  [anon_sym_COLONs] = ":s",
  [anon_sym_COLONf] = ":f",
  [anon_sym_COLONsf] = ":sf",
  [sym_source_file] = "source_file",
  [sym_automata_desc] = "automata_desc",
  [sym_statements] = "statements",
  [sym_statement] = "statement",
  [sym_state_spec] = "state_spec",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_statements_repeat1] = "statements_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_automata] = sym_automata,
  [sym_name] = sym_name,
  [sym_alphabet] = sym_alphabet,
  [sym_exec] = sym_exec,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_COLONs] = anon_sym_COLONs,
  [anon_sym_COLONf] = anon_sym_COLONf,
  [anon_sym_COLONsf] = anon_sym_COLONsf,
  [sym_source_file] = sym_source_file,
  [sym_automata_desc] = sym_automata_desc,
  [sym_statements] = sym_statements,
  [sym_statement] = sym_statement,
  [sym_state_spec] = sym_state_spec,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_statements_repeat1] = aux_sym_statements_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_automata] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_alphabet] = {
    .visible = true,
    .named = true,
  },
  [sym_exec] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLONs] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLONf] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLONsf] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_automata_desc] = {
    .visible = true,
    .named = true,
  },
  [sym_statements] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_state_spec] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_statements_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      if (lookahead == ',') ADVANCE(25);
      if (lookahead == '-') ADVANCE(26);
      if (lookahead == '.') ADVANCE(27);
      if (lookahead == ':') ADVANCE(8);
      if (lookahead == ';') ADVANCE(16);
      if (lookahead == 'a') ADVANCE(13);
      if (lookahead == 'e') ADVANCE(14);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '-') ADVANCE(26);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 2:
      if (lookahead == ';') ADVANCE(16);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 3:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 4:
      if (lookahead == 'a') ADVANCE(12);
      END_STATE();
    case 5:
      if (lookahead == 'c') ADVANCE(23);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(5);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 8:
      if (lookahead == 'f') ADVANCE(29);
      if (lookahead == 's') ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == 'm') ADVANCE(4);
      END_STATE();
    case 10:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 12:
      if (lookahead == 't') ADVANCE(3);
      END_STATE();
    case 13:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 14:
      if (lookahead == 'x') ADVANCE(6);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_automata);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'c') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'e') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'x') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_alphabet);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_exec);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_exec);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(21);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_COLONs);
      if (lookahead == 'f') ADVANCE(30);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_COLONf);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_COLONsf);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 1},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 7},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_automata] = ACTIONS(1),
    [sym_exec] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_COLONs] = ACTIONS(1),
    [anon_sym_COLONf] = ACTIONS(1),
    [anon_sym_COLONsf] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(28),
    [sym_alphabet] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(7), 1,
      anon_sym_DASH,
    ACTIONS(9), 1,
      anon_sym_COLONs,
    STATE(18), 1,
      sym_state_spec,
    ACTIONS(5), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
    ACTIONS(11), 2,
      anon_sym_COLONf,
      anon_sym_COLONsf,
  [18] = 3,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      sym_automata,
    STATE(4), 2,
      sym_automata_desc,
      aux_sym_source_file_repeat1,
  [29] = 3,
    ACTIONS(15), 1,
      sym_automata,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(6), 2,
      sym_automata_desc,
      aux_sym_source_file_repeat1,
  [40] = 4,
    ACTIONS(19), 1,
      sym_name,
    ACTIONS(21), 1,
      sym_exec,
    STATE(8), 1,
      sym_statement,
    STATE(24), 1,
      sym_statements,
  [53] = 3,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(25), 1,
      sym_automata,
    STATE(6), 2,
      sym_automata_desc,
      aux_sym_source_file_repeat1,
  [64] = 2,
    ACTIONS(30), 1,
      anon_sym_DOT,
    ACTIONS(28), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [72] = 3,
    ACTIONS(32), 1,
      anon_sym_SEMI,
    ACTIONS(34), 1,
      anon_sym_COMMA,
    STATE(11), 1,
      aux_sym_statements_repeat1,
  [82] = 3,
    ACTIONS(36), 1,
      sym_name,
    STATE(8), 1,
      sym_statement,
    STATE(25), 1,
      sym_statements,
  [92] = 3,
    ACTIONS(36), 1,
      sym_name,
    ACTIONS(38), 1,
      anon_sym_SEMI,
    STATE(19), 1,
      sym_statement,
  [102] = 3,
    ACTIONS(38), 1,
      anon_sym_SEMI,
    ACTIONS(40), 1,
      anon_sym_COMMA,
    STATE(12), 1,
      aux_sym_statements_repeat1,
  [112] = 3,
    ACTIONS(42), 1,
      anon_sym_SEMI,
    ACTIONS(44), 1,
      anon_sym_COMMA,
    STATE(12), 1,
      aux_sym_statements_repeat1,
  [122] = 2,
    ACTIONS(49), 1,
      anon_sym_DOT,
    ACTIONS(47), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [130] = 3,
    ACTIONS(36), 1,
      sym_name,
    ACTIONS(51), 1,
      anon_sym_SEMI,
    STATE(19), 1,
      sym_statement,
  [140] = 1,
    ACTIONS(53), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [145] = 1,
    ACTIONS(55), 2,
      ts_builtin_sym_end,
      sym_automata,
  [150] = 2,
    ACTIONS(57), 1,
      sym_alphabet,
    ACTIONS(59), 1,
      anon_sym_DASH,
  [157] = 1,
    ACTIONS(61), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [162] = 1,
    ACTIONS(42), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [167] = 1,
    ACTIONS(63), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [172] = 1,
    ACTIONS(65), 2,
      anon_sym_SEMI,
      anon_sym_COMMA,
  [177] = 1,
    ACTIONS(67), 2,
      ts_builtin_sym_end,
      sym_automata,
  [182] = 2,
    ACTIONS(36), 1,
      sym_name,
    STATE(19), 1,
      sym_statement,
  [189] = 1,
    ACTIONS(69), 1,
      anon_sym_SEMI,
  [193] = 1,
    ACTIONS(71), 1,
      anon_sym_SEMI,
  [197] = 1,
    ACTIONS(73), 1,
      sym_name,
  [201] = 1,
    ACTIONS(75), 1,
      anon_sym_DASH,
  [205] = 1,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
  [209] = 1,
    ACTIONS(79), 1,
      sym_name,
  [213] = 1,
    ACTIONS(81), 1,
      sym_name,
  [217] = 1,
    ACTIONS(83), 1,
      sym_name,
  [221] = 1,
    ACTIONS(85), 1,
      sym_name,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 18,
  [SMALL_STATE(4)] = 29,
  [SMALL_STATE(5)] = 40,
  [SMALL_STATE(6)] = 53,
  [SMALL_STATE(7)] = 64,
  [SMALL_STATE(8)] = 72,
  [SMALL_STATE(9)] = 82,
  [SMALL_STATE(10)] = 92,
  [SMALL_STATE(11)] = 102,
  [SMALL_STATE(12)] = 112,
  [SMALL_STATE(13)] = 122,
  [SMALL_STATE(14)] = 130,
  [SMALL_STATE(15)] = 140,
  [SMALL_STATE(16)] = 145,
  [SMALL_STATE(17)] = 150,
  [SMALL_STATE(18)] = 157,
  [SMALL_STATE(19)] = 162,
  [SMALL_STATE(20)] = 167,
  [SMALL_STATE(21)] = 172,
  [SMALL_STATE(22)] = 177,
  [SMALL_STATE(23)] = 182,
  [SMALL_STATE(24)] = 189,
  [SMALL_STATE(25)] = 193,
  [SMALL_STATE(26)] = 197,
  [SMALL_STATE(27)] = 201,
  [SMALL_STATE(28)] = 205,
  [SMALL_STATE(29)] = 209,
  [SMALL_STATE(30)] = 213,
  [SMALL_STATE(31)] = 217,
  [SMALL_STATE(32)] = 221,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 5, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statements, 1, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statements, 2, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_statements_repeat1, 2, 0, 0),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_statements_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 4, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statements, 3, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_state_spec, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_automata_desc, 4, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 7, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 6, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_automata_desc, 5, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [77] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_fap(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "fap",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
